### ISSUE TITLE
Kamu gets into an infinite loop with Okta on Safari

### ISSUE THREAD

**Issue by bitsapien** [ayr-ton/kamu#119]
The Safari browser behaves weird when trying to SSO for Kamu through Okta. It goes into a redirect loop.

Steps to reproduce:

1. Open your Okta dashboard on Safari.
2. Click on the Kamu link.
3. Wait for the redirect frenzy to start 😝

**Comment by macecchi** [comment]
I haven't been able to reproduce this bug for a long time now, so I'll close this issue for now. If anyone stills sees this behaviour let us know how you were able to reproduce it and I can open it again.
