### ISSUE TITLE
Switch to dark mode automatically based on browser preferences

### ISSUE THREAD

**Issue by macecchi** [ayr-ton/kamu#145]
With the introduction of dark mode on Kamu, we could be using new browser APIs to switch the app to dark mode automatically when it detects the user prefers dark mode, without needing to click on the toggle menu.

**As a** normal user
**When** I open Kamu
**I want to** see it in the color scheme that matches my browser's

## Acceptance Criteria

Browser on dark mode
**Given** I have a browser that supports the `prefers-color-scheme` API and on dark mode
**When** I open Kamu
**Then** I see it with the dark mode turned ON

Browser on light mode
**Given** I have a browser that supports the `prefers-color-scheme` API and on light mode
**When** I open Kamu
**Then** I see it with the dark mode turned OFF

Unsupported browser
**Given** I have a browser that does not support the `prefers-color-scheme` API 
**When** I open Kamu
**Then** I see it with the dark mode turned OFF

Browser preference does not override user preference
**Given** I have a browser that supports the `prefers-color-scheme` API and I have previously switched modes
**When** I open Kamu
**Then** I see it with the same mode as it was before

Analytics events
**Given** I have a browser that supports the `prefers-color-scheme` API and on dark mode
**When** Kamu switches to dark mode automatically
**Then** it sends the corresponding Analytics event

**Comment by IncognitaDev** [comment]
I'm working on it

**Comment by macecchi** [comment]
Hey @IncognitaDev, are you still working on this or can we make this issue available to someone else? Let us know if you need any support :)

**Comment by IncognitaDev** [comment]
Hey @macecchi, I'm having difficulties to make this issue, if anyone else wants to try, he can, I'll keep trying but for study purposes

**Comment by macecchi** [comment]
Might come in handy: https://github.com/GoogleChromeLabs/dark-mode-toggle

**Comment by IncognitaDev** [comment]
hey, I recived that message when I try to execute the migrations, can you help me?
![image](https://user-images.githubusercontent.com/48053804/78867372-61b04580-7a17-11ea-9a2f-da4d588616d8.png)
