### ISSUE TITLE
Report missing book

### ISSUE THREAD

**Issue by macecchi** [ayr-ton/kamu#174]
**As a** Kamu user
**When** I see a book in Kamu but I can't find the physical copy of it
**I want to** report that the book is missing
**So that** the library admins can know that it's missing and update it or remove it from the library

It's pretty common when having a library that sometimes a book goes missing from that location - maybe because a user borrowed the book and forgot to borrow on Kamu, someone misplaced it or something else. Usually people send an email asking where a book is, but when it cannot be found, it often is left on Kamu. And so the frustration repeats for the next person that looks for it.

The idea of this feature request is to have a report option on the book. Here are some possible use cases:
* Display a warning on the book itself, to let interested users that it was previously reported missing;
* Display a list of reports on the admin page, so that library admins can check follow up on them and update or remove the books
* Send an automated notification to the library users asking if someone knows where the book is
etc.

**Comment by erikaya** [comment]
@macecchi can I get this issue?

**Comment by macecchi** [comment]
@erikaya Of course! Let me know if you need any help ;)
