### ISSUE TITLE
Migrate React tests to react-testing-library

### ISSUE THREAD

**Issue by macecchi** [ayr-ton/kamu#187]
## Context
A while ago we started coding unit tests using Enzyme's **shallow rendering**.
After **react-testing-library** was popularized, bringing a more functional approach to React testing, we decided to stop using Enzyme and mount the full components using react-testing-library instead.

The main idea of RTL is that your tests should be focusing on actual user behavior and expected outcomes, instead of getting too close to implementation details, which is usually the case when testing using only shallow rendering of components - we end up testing component props, state, the existence of child React components etc. instead of actually testing what the behavior should be.

## Goal
Many of the old tests were already migrated from Enzyme to RTL. However, there are still a few components using shallow tests. The idea of this issue is working towards replacing those to RTL too, so that we can decommission Enzyme entirely on Kamu. It's also part of the migration to analyze what behaviors should be tested - not every enzyme test will become a RTL test.

**Comment by erikaya** [comment]
I'd love to work on that! :D

**Comment by macecchi** [comment]
@erikaya feel free to work on it! this one @lucashanke can help me review because I'm not that used to RTL yet hahaha
