### ISSUE TITLE
Add a Book to Wishlist

### ISSUE THREAD

**Issue by ayr-ton** [ayr-ton/kamu#29]
Depends on #70 

As a **user**
I want to **add a book to the wishlist**
So **the office could buy a copy**

**Comment by erikatech** [comment]
Each office will have its own wishlist, right? Is there any checking that must be done in order to guarantee that I can add a book only to the wishlist of the office I belong to?

**Comment by ayr-ton** [comment]
Good question. 
@flavia-by-flavia What do you think?

**Comment by ayr-ton** [comment]
@erikatech I have talked to Flávia and she said that is one per office/library.
