### ISSUE TITLE
Improve CONTRIBUTING.md

### ISSUE THREAD

**Issue by ayr-ton** [ayr-ton/kamu#33]
Let's discuss here improvements opportunities to the CONTRIBUTING.md that could help new collaborators.

**Comment by ayr-ton** [comment]
I'm in love with this one: https://github.com/Enegrecer/enegrecer-web/blob/master/.github/CONTRIBUTING.md

**Comment by marti1125** [comment]
Hi! @ayr-ton I could suggest you this https://gist.github.com/PurpleBooth/b24679402957c63ec426

**Comment by ayr-ton** [comment]
@marti1125 hmmmm... that's nice

**Comment by ayr-ton** [comment]
Added the new style and code of conduct, as suggested by @marti1125

**Comment by alljp** [comment]
Also, the email id is not added in the **Enforcement** section

```Instances of abusive, harassing, or otherwise unacceptable behavior may be reported by contacting the project team at [INSERT EMAIL ADDRESS]. All complaints will be reviewed and investigated and will result in a response that is deemed necessary and appropriate to the circumstances.```
