### ISSUE TITLE
Run "Getting started" from README.md on Mac OS and provide improvements

### ISSUE THREAD

**Issue by ayr-ton** [ayr-ton/kamu#42]

**Comment by felixdollack** [comment]
Hi @ayr-ton,
I tried following the provided instructions and made some comments to improve them.
I did the following:
* Add a macOS specific subsection with instructions to install node.js
* Move "Okta Preview" to the end of the instruction section (optional)

**Comment by ayr-ton** [comment]
Thank you, @felixdollack o/
