### ISSUE TITLE
Suggest a different venv name

### ISSUE THREAD

**Issue by anapaulagomes** [ayr-ton/kamu#57]
Currently the README suggests that the virtual environment share the same folder of a regular module (`python3 -m venv kamu`). I'd like to suggest changing the venv name to something else (maybe the conventional `venv`?) and keep them separated. Otherwise, if we decided using something else as virtual environment we need to delete each file or folder. Even the `.gitignore` is difficult to manage when we need to add all the different stuff from the venv and the module. For instance: the venv module created `kamu/lib64` on my repository but this wasn't ignored before.

**Comment by ayr-ton** [comment]
I like the idea o/

**Comment by anapaulagomes** [comment]
Don't forget to update the .gitignore file. :)
