### ISSUE TITLE
Logo contribution

### ISSUE THREAD

**Issue by reallinfo** [ayr-ton/kamu#58]
Hello! @ayr-ton 

I have designed a functional logo for your repository. Please tell me what you think of them. And if you want, let's finish this together. I guess, the top logo will look very good in the readme file.

![1](https://user-images.githubusercontent.com/36298335/46866723-356c3680-ce2b-11e8-90e5-9692adfe5d3a.jpg)

**Comment by ayr-ton** [comment]
@flavia-by-flavia @macecchi @erikatech look at that 👯

**Comment by flavia-by-flavia** [comment]
I would like to keep the same logo that we have inside Kamu. Maybe @reallinfo suggested one because we don't have any print screen from the current kamu in our readme. I will open an issue on that! ;)

**Comment by ayr-ton** [comment]
@flavia-by-flavia We will close this one?

**Comment by flavia-by-flavia** [comment]
Sure!

Em qui, 27 de dez de 2018 às 21:54, Ayrton Araújo <notifications@github.com>
escreveu:
