### ISSUE TITLE
Make test coverage report work

### ISSUE THREAD

**Issue by flavia-by-flavia** [ayr-ton/kamu#62]
**As a Github user**
**When I** go to README
**I want to** see the test coverage status
**So I** can decide to make improvements in test coverage for the code

**Acceptance Criteria**
**Given** I am in the readme doc
**When** I scroll down to the Code Coverage button
**Then** I see the percentage of test that's covering the code

**How it is now:**
<img width="645" alt="screen shot 2018-10-17 at 21 37 39" src="https://user-images.githubusercontent.com/13057603/47128043-51217380-d255-11e8-9f71-25759943aaff.png">

**How it should be:**
<img width="421" alt="screen shot 2018-10-17 at 21 38 18" src="https://user-images.githubusercontent.com/13057603/47128059-66969d80-d255-11e8-9f42-e6e24294fdb3.png">

**ATTENTION only for the test coverage button. The other ones don't need to be changed!**

**Comment by philmillman** [comment]
looks like it needs to be set up here: https://codeclimate.com/github/ayr-ton/kamu 

![image](https://user-images.githubusercontent.com/3722211/47129913-4a9af800-d265-11e8-8281-9a142c123843.png)

**Comment by flavia-by-flavia** [comment]
Hi @philmillman . You may be right, but when I click, I don't have access.

<img width="784" alt="screen shot 2018-10-18 at 18 26 09" src="https://user-images.githubusercontent.com/13057603/47189688-6bb22600-d303-11e8-91dc-34136d51213d.png">

Maybe only @ayr-ton can set it up. @ayr-ton can you try to click on the umbrella?

**Comment by ayr-ton** [comment]
@philmillman We want the circle-ci code that this button points to. We know where it is.

**Comment by philmillman** [comment]
Sorry, my bad. I'll take a look tomorrow!
