### ISSUE TITLE
Update pysaml2 to fix known vulnerability

### ISSUE THREAD

**Issue by ayr-ton** [ayr-ton/kamu#87]
https://github.com/ayr-ton/kamu/network/alerts

Currently, there's no updated version that fixes this issue, I'm one of the maintainers of this plugin.

As this plugin is not an authentication backend for Django we may or update the plugin for supporting this or migrate to a new one that supports this.

Also, there's always the possibility of just fixing the initialization vector across encryptions and release a new plugin version with this.

**Comment by macecchi** [comment]
pysaml2 was already updated.
